name: Continuous Persistent VPS with Pterodactyl

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:
    inputs:
      VPS_IP:
        description: 'Enter the VPS IP (from Tailscale)'
        required: true
        default: '127.0.0.1'

jobs:
  vps-session:
    runs-on: ubuntu-latest
    timeout-minutes: 350  # Just under 6 hours

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set hostname to biralo
        run: sudo hostnamectl set-hostname biralo

      - name: Download VPS backup (if any)
        uses: actions/download-artifact@v4
        with:
          name: vps-backup
          path: ./backup
        continue-on-error: true

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y tmate curl unzip sudo net-tools neofetch

      - name: Install Tailscale official script
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Restore Tailscale state
        run: |
          if [ -f ./backup/tailscaled.state ]; then
            sudo mkdir -p /var/lib/tailscale
            sudo cp ./backup/tailscaled.state /var/lib/tailscale/tailscaled.state
            sudo chmod 600 /var/lib/tailscale/tailscaled.state
          fi

      - name: Start Tailscale
        run: |
          sudo tailscaled &
          sleep 8
          sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTHKEY }} --hostname=biralo || echo "Tailscale already up"

      - name: Create user biralo with sudo
        run: |
          if ! id -u biralo >/dev/null 2>&1; then
            sudo useradd -m -s /bin/bash biralo
            echo "biralo:biralo" | sudo chpasswd
            sudo usermod -aG sudo biralo
            echo "biralo ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/biralo
          fi

      - name: Set VPS IP from input
        run: |
          echo "VPS_IP=${{ github.event.inputs.VPS_IP }}" >> $GITHUB_ENV
          echo "Using IP: ${{ github.event.inputs.VPS_IP }}"

      - name: Install prerequisites for Pterodactyl (PHP 8.3)
        run: |
          sudo apt update
          sudo apt install -y software-properties-common curl unzip sudo net-tools neofetch
          sudo add-apt-repository ppa:ondrej/php -y
          sudo apt update
          sudo apt install -y \
            php8.3 php8.3-cli php8.3-gd php8.3-mysql php8.3-mbstring \
            php8.3-bcmath php8.3-xml php8.3-curl php8.3-zip php8.3-fpm \
            mariadb-server mariadb-client redis-server \
            nginx git zip unzip tar composer docker.io
          sudo systemctl enable --now mariadb redis-server docker nginx php8.3-fpm
          php -v

      - name: Install Pterodactyl Panel
        run: |
          sudo mkdir -p /var/www/pterodactyl
          cd /var/www/pterodactyl
          curl -Lo panel.tar.gz https://github.com/pterodactyl/panel/releases/latest/download/panel.tar.gz
          tar -xzvf panel.tar.gz
          composer install --no-dev --optimize-autoloader
          php artisan key:generate --force
          php artisan p:environment:setup \
            --author="Admin" \
            --url="http://${VPS_IP}" \
            --timezone="UTC" \
            --cache="redis" \
            --session="redis" \
            --queue="redis" \
            --mysql-host="127.0.0.1" \
            --mysql-port="3306" \
            --mysql-database="panel" \
            --mysql-username="pterodactyl" \
            --mysql-password="password" \
            --redis-host="127.0.0.1" \
            --redis-password="null" \
            --redis-port="6379" \
            --settings-ui=true \
            --telemetry=true
          sudo chown -R www-data:www-data /var/www/pterodactyl
          sudo chmod -R 755 /var/www/pterodactyl

      - name: Create Pterodactyl admin user
        run: |
          cd /var/www/pterodactyl
          php artisan p:user:make \
            --email="virathero9840@gmail.com" \
            --username="98984040Heroo_" \
            --name-first="Virat" \
            --name-last="Raj" \
            --password="BlackHero" \
            --admin=1

      - name: Install Pterodactyl Wings
        run: |
          sudo mkdir -p /etc/pterodactyl
          curl -Lo wings https://github.com/pterodactyl/wings/releases/latest/download/wings_linux_amd64
          sudo mv wings /usr/local/bin/wings
          sudo chmod +x /usr/local/bin/wings
          echo "Wings installed. Run manually: wings --config /etc/pterodactyl/config.yml"

      - name: Start tmate session for SSH access
        uses: mxschmitt/action-tmate@v3

      - name: Sleep to keep VPS alive
        run: sleep 21600  # 6 hours

      - name: Backup VPS data and tailscale state
        run: |
          sudo mkdir -p backup
          sudo cp /var/lib/tailscale/tailscaled.state backup/
          zip -r backup.zip backup

      - name: Upload VPS backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: vps-backup
          path: backup.zip
